<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="main"/>
    <title>GRUrl - Questions</title>
</head>
<body>
<div class="body">
    <h1>Questions And Answers</h1>

    <div class="qa">
        <div class="question">
            Q: What does GRUrl do?
        </div>
        <div class="answer">
            A: GRUrl is a tool to provide a very short URL that effectively acts as an alias for another URL
            which is potentially a lot longer.  For example, a URL like http://need a long url to put here could
            be accessed with the much shorter http://grurl.com/3d7.
        </div>
    </div>
    
    <div class="qa">
        <div class="question">
            Q: Why would I want to do that?
        </div>
        <div class="answer">
            A: There are a number of reasons you might want to take advantage of GRUrl.  Maybe you want to post
            a URL in a tool that limits the number of allowed characters (like
            <a href="http://www.twitter.com">Twitter</a>, for example).  Long URLs often do not work properly
            in all email clients.  If you email a long URL to someone, depending on a number of factors, the
            recipient may or may not be able to click on the link in their email client and get the desired
            result.  A short URL like those generated by GRUrl does not suffer from that problem.
        </div>
    </div>

    <div class="qa">
        <div class="question">
            Q: I want to visit sites that I shouldn't be visiting and I don't want those URLs to show up
            in my browser history.  If I access those sites through GRUrl, will that help me hide my tracks?
        </div>
        <div class="answer">
            A: No.  When you access a URL through GRUrl your browser eventually redirects to the real site
            just as if you had accessed that URL directly.  If you are trying to disguise your browsing habits,
            GRUrl is not going to help you.  Sorry.
        </div>
    </div>

    <div class="qa">
        <div class="question">
            Q: Does GRUrl keep track of what sites I visit or any of my personal information?
        </div>
        <div class="answer">
            A: No.  GRUrl does not know anything at all about you.  We simply generate URLs and respond to
            requests for those URLs by redirecting the request to the &quot;real&quot; site.  At no time
            does GRUrl gather any personal information.
        </div>
    </div>

    <div class="qa">
        <div class="question">
            Q: Do I need any special software installed on my computer to use GRUrl?
        </div>
        <div class="answer">
            A: No.  GRUrl uses standards based technology.  URLs generated by GRUrl will work just fine
            in practically any web browser on practically any operating system.
        </div>
    </div>

    <div class="qa">
        <div class="question">
            Q: How much does it cost?
        </div>
        <div class="answer">
            A: GRUrl is free to use.
        </div>
    </div>

    <div class="qa">
        <div class="question">
            Q: Do I need to sign up or create an account to use GRUrl?
        </div>
        <div class="answer">
            A: No.  Just visit the site and start using it.  That is all there is to it.
        </div>
    </div>

    <div class="qa">
        <div class="question">
            Q: Why is it called GRUrl?
        </div>
        <div class="answer">
            A: GRUrl is short for &quot;Groovy URL&quot;.  A Groovy URL is a URL that is Groovier than any other. (wink)
        </div>
    </div>

</div>
</body>
</html>
